### ISSUE TITLE
Record interaction deduping causing incomplete titles to be recorded.

### ISSUE THREAD

**Issue by jmiller101** [range-labs/range-sync#46]
- Extension version: 4.2.2
- Integration: Asana, GitHub

**Expected Behavior:**

The page is reported to Range once it has completely loaded.

**Actual Behavior:**

Unloaded pages are sent to Range.

**Steps to Reproduce the Problem:**

1. Go to Asana
1. Click through a few cards
1. Check your compose sidebar

**Comment by stephyeung** [comment]
Also being reported with Clubhouse

**Comment by jmiller101** [comment]
Closing this after confirming that v2.4.3 has resolved the problem.
