### ISSUE TITLE
Add support for Phabricator code reviews

### ISSUE THREAD

**Issue by tinawright** [range-labs/range-sync#5]
I'd like code review updates. 

I think the minimal viable would be diff number & description with link to the diff. 

nice to have: status of the diff.

**Comment by dpup** [comment]
Hi Tina, we don't have access to a phabricator instance but would love to make this work. One issue with phrabricator is that it is usually self-hosted which will likely make it hard to target via the Chrome Extension. Could you share the URL pattern that you'd want this to trigger on?

Another option is to do a backend integration, you can create a webhook for your organization and then post events which will generate suggestions. You can find out more here:
https://help.range.co/en/articles/2383870-custom-range-integrations
